README.md
docs/install_ocp_debian_apache_ssl.rst

https://github.com/FreedomCoop/valuenetwork/issues/14

New doc for install in debian, apache and ssl server.

---

valuenetwork/valueaccounting/management.py
work/__init__.py
work/templates/notification/comment_membership_request/full.txt
work/templates/notification/comment_membership_request/short.txt

I would like to merge *comments_notifications* branch into master to deploy in testocp to test with real emails.
Please, note that to run `./manage.py migrate` is necessary in order to activate the subscription (just to fire sync_db, no migrate files pending)

Comments notification

---

work/management/commands/reassign-wallet-addresses.py

Intended for development only.
Fixes #199.

implement script to reassign wallet addresses not controlled by the local wallet

---

valuenetwork/valueaccounting/admin.py
valuenetwork/valueaccounting/forms.py
valuenetwork/valueaccounting/models.py
valuenetwork/valueaccounting/views.py
work/templates/work/process_logging.html
work/urls.py
work/views.py

I think I got all of the EconomicResource.quantity fields out of all the forms and the one form where a quantity field was needed now has a field called event_quantity (it was used in process logging, and has been tested with its new field).

Resource quantities

---

valuenetwork/api/schemas/Agent.py
valuenetwork/valueaccounting/models.py

Put method in models (careless programmer error earlier)
Change to "Organization" => VF

Fixed members query

---

valuenetwork/api/schemas/Agent.py

Added photo url field to Agent, for the thumbnails on the UI.
Added organizationMembers method, for the members section on project page.

photo_url, members method

---

faircoin_nrp/daemon/daemon.py.sample
faircoin_nrp/electrum_fair_nrp.py
valuenetwork/valueaccounting/process_faircoin_requests.py

New faircoin addresses are managed by the wallet as usual, or from a file which have private keys to import to the wallet. A variable in local_settings.py defines the behaviour NEW_FAIRCOIN_ADDRESSES_FILE = absolute/path/to/file

Address from file

---

requirements.txt

Upgrade to django 1.11 and django-fobi 0.12.2

django 1.11

---

multicurrency/forms.py
multicurrency/templates/multicurrency_auth.html
multicurrency/urls.py
multicurrency/utils.py
multicurrency/views.py

The "create new chpchap user" button is currently working, but when the user is created it cannot authenticate automatically until the user confirms the email in the inbox of his/her email. This change in chipchap api has been demanded but maybe put better this feature in testing/production without the authentication, as it seems it can take long.

Create chipchap user

---

valuenetwork/templates/valueaccounting/edit_xbill.html
valuenetwork/valueaccounting/models.py

This branch fixes a couple of bugs in recipes that have been tested and found to work in testocp, but are not yet deployed to prod ocp. And people want to start using recipes in prod ocp.
So please merge and deploy.

Fix recipes

---

work/templates/work/process_logging.html
work/views.py

if no work resource types found

fix bug where work/process-logging crashes

---

work/views.py

All resource types

---

valuenetwork/valueaccounting/models.py
work/views.py

This PR fixes some problems with value distributions using faircoins.

Fix distribution

---

valuenetwork/valueaccounting/models.py
work/templates/work/fake_kanban.html
work/urls.py
work/views.py

this is a kanban experiment coming from some telegram conversations. If is read-only, not connected to any menus, and does not change any data or operational code. Should be safe to deploy.

first draft of fake-kanban

---

work/templates/work/fake_kanban.html

A couple of improvements on the fake kanban, still all safe to deploy

Fake kanban 2

---

work/views.py

caused a key error on "event_quantity"

fix bug where logging uninventoried process output

---

valuenetwork/valueaccounting/models.py

by using the decimal hours widget
instead of the broken hours/minutes widget

fix bug in work event change form

---

work/templates/work/fake_kanban.html
work/templates/work/members_agent.html

@bum2 - this is still experimental and will be replaced by Kamasi sooner or later, but in the meantime, people think it is useful and would like it added to the project submenu, which this PR does.
Please take a quick look and see if the way I added it to the submenu is ok with you.

add kanbans to project submenu

---

valuenetwork/valueaccounting/forms.py
valuenetwork/valueaccounting/models.py
valuenetwork/valueaccounting/views.py
work/templates/work/process_logging.html

In the work app, added is-contribution flag and name to work event edit, changed name, added to display.

work event edit enhancements

---

valuenetwork/valueaccounting/forms.py

in Unplanned Work logging form

change Is contribution to Request payment

---

tox.ini

This should fix some of the tests, still a couple broken though.

Bring tox dependencies up-to-date with requirements.txt.

---

valuenetwork/login_required_middleware.py
valuenetwork/templates/account/login.html

Passing 'next' parameter through POST doesn't seem to be working so passing via GET in form action.
Fixes #403

After signing in redirect back to the page that required sign in.

---

requirements.txt
valuenetwork/api/models.py
valuenetwork/api/schema.py
valuenetwork/api/schemas/Agent.py
valuenetwork/api/schemas/Commitment.py
valuenetwork/api/schemas/EconomicEvent.py
valuenetwork/api/schemas/EconomicResource.py
valuenetwork/api/schemas/Organization.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/api/types/Commitment.py
valuenetwork/api/types/EconomicEvent.py
valuenetwork/api/types/EconomicResource.py
valuenetwork/api/types/Process.py
valuenetwork/valueaccounting/models.py

This includes an api mutation to update some fields on the agent.

Api agent mutations

---

valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/api/types/Plan.py
valuenetwork/valueaccounting/models.py

Api extensions: kanbanState, memberRelationships

---

valuenetwork/api/models.py
valuenetwork/api/schema.py
valuenetwork/api/schemas/Agent.py
valuenetwork/api/schemas/EconomicEvent.py
valuenetwork/api/schemas/OrganizationClassification.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/api/types/Exchange.py
valuenetwork/api/types/apps.py
valuenetwork/valueaccounting/models.py

Added some filters for economic events to the api, to support some data analytics for FreedomCoop.

Api extensions

---

valuenetwork/api/schemas/Process.py
valuenetwork/api/tests.py
valuenetwork/api/types/EconomicResource.py
valuenetwork/api/types/Process.py
valuenetwork/valueaccounting/models.py

DO NOT MERGE.  I will merge it in conjunction with the UI changes going into production, they need to be coordinated.

Changed process.plannedDuration to .plannedFinish. 

---

valuenetwork/api/schemas/EconomicEvent.py

Merge only by @ivanminutillo after testing with UI.  Otherwise, please don't merge.

Fix current location bug on create economic event with resource.

---

valuenetwork/api/schemas/Plan.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/valueaccounting/models.py

(using the scope from the last/top process type in the recipe)

removed scope from api on create plan from recipe

---

valuenetwork/api/schemas/EconomicEvent.py
valuenetwork/api/schemas/EconomicResource.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/api/types/EconomicResource.py
valuenetwork/valueaccounting/models.py

Simple resource search, add url to resource api, bug fixes.
Please DON'T MERGE, I will do it in coordination with the UI changes.

Api extensions faircoop

---

valuenetwork/api/schema.py
valuenetwork/api/schemas/Agent.py
valuenetwork/api/schemas/Commitment.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/valueaccounting/models.py

Added person and organization delete to the api (for LearnDeep).
Added ability to uncommit to a commitment in the api.
Added agent.commitmentsMatchingSkills method.

Api extensions faircoop: agent delete and uncommit

---

valuenetwork/api/schema.py
valuenetwork/api/schemas/AgentResourceClassification.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/api/types/AgentResourceClassification.py
valuenetwork/api/types/apps.py
valuenetwork/valueaccounting/models.py

also fix for authorization for agent to save own info

api: person skills create/delete

---

valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/valueaccounting/models.py

Please don't merge until the UI app is tested against testocp.

added api search for agent plans, processes, commitments

---

valuenetwork/valueaccounting/models.py

Distribution

---

valuenetwork/urls.py
valuenetwork/valueaccounting/models.py

Another deprecation warning, remove all permalink decorators

Remove permalink decorators and update admin urls

---

account/decorators.py
account/middleware.py
account/mixins.py
account/models.py
account/views.py
valuenetwork/login_required_middleware.py
work/views.py

Use is_authenticated as an attribute

---

valuenetwork/api/types/Agent.py
valuenetwork/valueaccounting/models.py
valuenetwork/valueaccounting/utils.py
valuenetwork/valueaccounting/views.py
work/views.py

I changed every call to cmp(), one step less  to python3 :smile:

Fix sorts with lambda and cmp
